import { SearchData } from "./filterInterfaces.ts";

export const boreholeSearchData: SearchData[] = [
  {
    id: 0,
    type: "Input",
    label: "originalName",
    value: "originalName",
  },
  {
    id: 1,
    type: "Input",
    label: "projectName",
    value: "projectName",
  },
  {
    id: 2,
    type: "Input",
    label: "alternate_name",
    value: "name",
  },
  {
    id: 3,
    type: "Dropdown",
    label: "restriction",
    value: "restrictionId",
    schema: "restriction",
  },
  {
    id: 4,
    type: "Date",
    label: "restriction_until",
    value: "restrictionUntilFrom",
    placeholder: "afterdate",
    hasTwoFields: true,
  },
  {
    id: 5,
    type: "Date",
    label: "",
    value: "restrictionUntilTo",
    placeholder: "beforedate",
    hasTwoFields: true,
  },
  {
    id: 6,
    type: "NullableBoolean",
    label: "nationalInterest",
    value: "nationalInterest",
  },
  {
    id: 7,
    type: "Dropdown",
    label: "borehole_type",
    value: "typeId",
    schema: "borehole_type",
  },
  {
    id: 8,
    type: "Dropdown",
    label: "purpose",
    value: "purposeId",
    schema: "extended.purpose",
  },
  {
    id: 9,
    type: "Dropdown",
    label: "boreholeStatus",
    value: "statusId",
    schema: "extended.status",
  },
  {
    id: 10,
    type: "Input",
    label: "totaldepth",
    value: "totalDepthMin",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "from",
  },
  {
    id: 11,
    type: "Input",
    label: "",
    value: "totalDepthMax",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "to",
  },
  {
    id: 12,
    type: "Input",
    label: "top_bedrock_fresh_md",
    value: "topBedrockFreshMdMin",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "from",
  },
  {
    id: 13,
    type: "Input",
    label: "",
    value: "topBedrockFreshMdMax",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "to",
  },
  {
    id: 14,
    type: "Input",
    label: "top_bedrock_weathered_md",
    value: "topBedrockWeatheredMdMin",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "from",
  },
  {
    id: 15,
    type: "Input",
    label: "",
    value: "topBedrockWeatheredMdMax",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "to",
  },

  {
    id: 16,
    type: "NullableBoolean",
    label: "hasGroundwater",
    value: "hasGroundwater",
  },
  {
    id: 17,
    type: "NullableBoolean",
    label: "topBedrockIntersected",
    value: "topBedrockIntersected",
  },
  {
    id: 18,
    type: "Boolean",
    label: "hasGeometry",
    value: "hasGeometry",
  },
];
