export const boreholeSearchData = [
  {
    id: 0,
    type: "Dropdown",
    label: "borehole_type",
    value: "typeId",
    schema: "borehole_type",
    multiple: false,
    search: false,
  },
  {
    id: 2,
    type: "Dropdown",
    label: "purpose",
    value: "purposeId",
    schema: "extended.purpose",
    multiple: false,
    search: false,
  },
  {
    id: 2,
    type: "Dropdown",
    label: "boreholeStatus",
    value: "statusId",
    schema: "extended.status",
    multiple: false,
    search: false,
  },
  {
    id: 16,
    type: "Input",
    label: "totaldepth",
    value: "totalDepthMin",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "from",
  },
  {
    id: 17,
    type: "Input",
    label: "",
    value: "totalDepthMax",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "to",
  },
  {
    id: 20,
    type: "Input",
    label: "top_bedrock_fresh_md",
    value: "topBedrockFreshMdMin",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "from",
  },
  {
    id: 21,
    type: "Input",
    label: "",
    value: "topBedrockFreshMdMax",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "to",
  },
  {
    id: 26,
    type: "Input",
    label: "top_bedrock_weathered_md",
    value: "topBedrockWeatheredMdMin",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "from",
  },
  {
    id: 27,
    type: "Input",
    label: "",
    value: "topBedrockWeatheredMdMax",
    isNumber: true,
    inputType: "number",
    hasTwoFields: true,
    placeholder: "to",
  },

  {
    id: 29,
    type: "TriStateBoolean",
    label: "hasGroundwater",
    value: "hasGroundwater",
    hasUnknown: true,
    to: false,
  },

  {
    id: 30,
    type: "Boolean",
    label: "topBedrockIntersected",
    value: "topBedrockIntersected",
    hasUnknown: true,
    to: false,
  },
  {
    id: 31,
    type: "Boolean",
    label: "hasGeometry",
    value: "hasGeometry",
    hasUnknown: true,
    to: false,
  },
];
