services:
  db:
    extends:
      file: ../../docker-compose.yml
      service: db
    # override the default configuration
    volumes:
      - /var/lib/postgresql/data
  target-db:
    image: postgis/postgis:15-3.4-alpine
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: SLICKERMONTANA
      POSTGRES_PASSWORD: YELLOWYARD
      POSTGRES_DB: ANGRYFELONY
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 3051:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: TRINITYFEED
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./config/pgadmin4-servers.json:/pgadmin4/servers.json
    entrypoint:
      - /bin/sh
      - -c
      - |
        /bin/echo 'db:5432:bdms:SPAWNPLOW:YELLOWSPATULA' > /tmp/.pgpass
        /bin/echo 'target-db:5432:ANGRYFELONY:SLICKERMONTANA:YELLOWYARD' >> /tmp/.pgpass
        chmod 0600 /tmp/.pgpass
        /entrypoint.sh
  api:
    extends:
      file: ../../docker-compose.yml
      service: api
    build:
      args:
        - VERSION=0.0.99
        - REVISION=test
    environment:
      # use development environment to enable seeding the database
      - ASPNETCORE_ENVIRONMENT=Development
  minio:
    extends:
      file: ../../docker-compose.yml
      service: minio
