# Default values for the swissgeol-boreholes-extern-sync application.
# This is a YAML-formatted file.

#
# General application configuration
#
app:
  # -- The tag name of the Docker image tag to be deployed
  # -- e.g. v2.0.506
  version: v2.1.1462
  # -- The timezone which will be used in the application
  timezone: Europe/Zurich
  # -- The schedule for the cron job
  # -- Refer to https://en.wikipedia.org/wiki/Cron for valid values.
  schedule: 0 0 * * *

configuration:
  # -- The default workgroup name to assign the borehole to if there is no matching workgroup in the target database
  targetDefaultWorkgroupName: Sync
  # -- The default user subject/identifier to assign the synced boreholes to.
  targetDefaultUserSub: sub_admin

# Database configuration (source and target)
# All database values are stored as secrets and assembled into connection strings.
db:
  source:
    # -- The hostname of the source database server (stored as secret)
    host:
    # -- The port of the source database server (stored as secret)
    port: 5432
    # -- The name of the source database (stored as secret)
    name:
    # -- The username for the source database (stored as secret)
    username:
    # -- The password for the source database (stored as secret)
    password:
  target:
    # -- The hostname of the target database server (stored as secret)
    host:
    # -- The port of the target database server (stored as secret)
    port:
    # -- The name of the target database (stored as secret)
    name:
    # -- The username for the target database (stored as secret)
    username:
    # -- The password for the target database (stored as secret)
    password:
