apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.app.schedule | default "0 0 * * *" }}"
  timeZone: "{{ .Values.app.timezone | default "Europe/Zurich" }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        spec:
          automountServiceAccountToken: false
          securityContext:
            runAsUser: 70
            runAsGroup: 70
            fsGroup: 70
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: {{ .Release.Name }}
              image: ghcr.io/swisstopo/swissgeol-boreholes-suite-view-sync:{{ required "app.version is required" .Values.app.version }}
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 200m
                  memory: 512Mi
                  ephemeral-storage: 1Gi
                limits:
                  cpu: 1000m
                  memory: 1Gi
                  ephemeral-storage: 2Gi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              volumeMounts:
              - name: tmp
                mountPath: /tmp
              env:
                - name: SOURCE_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabaseHost
                - name: SOURCE_DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabasePort
                - name: SOURCE_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabaseName
                - name: SOURCE_DB_SCHEMA
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabaseSchema
                - name: SOURCE_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabaseUsername
                - name: SOURCE_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabasePassword
                - name: TARGET_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: targetDatabaseHost
                - name: TARGET_DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: targetDatabasePort
                - name: TARGET_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: targetDatabaseName
                - name: TARGET_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: targetDatabaseUsername
                - name: TARGET_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: targetDatabasePassword
                - name: TZ
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: timezone
          volumes:
          - name: tmp
            emptyDir: {}
          restartPolicy: Never
      backoffLimit: 4
