using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BDMS.Migrations;
#pragma warning disable CA1505

/// <inheritdoc />
public partial class AddNewLithologyCodelists : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            SELECT setval('bdms.codelist_id_cli_seq', (SELECT MAX(id_cli) FROM bdms.codelist));
            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('lithology_uncon_main', 'LBo', 'large boulder', 'Grossblock', 'bloc grand', 'masso grande', 10),
                ('lithology_uncon_main', 'Bo', 'boulder', 'Block', 'bloc', 'masso', 20),
                ('lithology_uncon_main', 'Co', 'cobbles', 'Steine', 'galets', 'ciottoli', 30),
                ('lithology_uncon_main', 'Gr', 'gravel', 'Kies', 'gravier', 'ghiaia', 35),
                ('lithology_uncon_main', 'CGr', 'coarse gravel', 'Grobkies', 'gravier grossier', 'ghiaia grossa', 40),
                ('lithology_uncon_main', 'MCGr', 'medium-coarse gravel', 'Mittel-Grobkies', 'gravier moyen-grossier', 'ghiaia media-grossa', 50),
                ('lithology_uncon_main', 'MGr', 'medium gravel', 'Mittelkies', 'gravier moyen', 'ghiaia media', 60),
                ('lithology_uncon_main', 'FMGr', 'fine-medium gravel', 'Fein-Mittelkies', 'gravier fin-moyen', 'ghiaia fine-media', 70),
                ('lithology_uncon_main', 'FGr', 'fine gravel', 'Feinkies', 'gravier fin', 'ghiaia fine', 80),
                ('lithology_uncon_main', 'Sa', 'sand', 'Sand', 'sable', 'sabbia', 85),
                ('lithology_uncon_main', 'CSa', 'coarse sand', 'Grobsand', 'sable grossier', 'sabbia grossa', 90),
                ('lithology_uncon_main', 'MCSa', 'medium-coarse sand', 'Mittel-Grobsand', 'sable moyen-grossier', 'sabbia media-grossa', 100),
                ('lithology_uncon_main', 'MSa', 'medium sand', 'Mittelsand', 'sable moyen', 'sabbia media', 110),
                ('lithology_uncon_main', 'FMSa', 'fine-medium sand', 'Fein-Mittelsand', 'sable fin-moyen', 'sabbia fine-media', 120),
                ('lithology_uncon_main', 'FSa', 'fine sand', 'Feinsand', 'sable fin', 'sabbia fine', 130),
                ('lithology_uncon_main', 'Si', 'silt', 'Silt', 'limon', 'limo', 140),
                ('lithology_uncon_main', 'Cl', 'clay', 'Ton', 'argile', 'argilla', 150),
                ('lithology_uncon_main', 'Pt', 'peat', 'Torf', 'tourbe', 'torba', 160),
                ('lithology_uncon_main', 'Or', 'organic soil', 'Organischer Boden', 'sol organique', 'suolo organico', 170),
                ('lithology_uncon_main', 'Hu', 'humus', 'Humus', 'humus', 'humus', 180),
                ('lithology_uncon_main', 'An', 'anthropogenic soil', 'Anthropogener Boden', 'sol anthropique', 'suolo antropico', 190),
                ('lithology_uncon_main', 'Ba', 'backfill', 'Auffüllung', 'remblai', 'rinterro', 200),
                ('lithology_uncon_main', 'oth', 'other', 'anderer', 'autre', 'altro', 210),
                ('lithology_uncon_main', 'ns', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 220);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('lithology_uncon_secondary', 'lbo', 'coarse blocky / with large blocks', 'grossblockig / mit Grossblöcken', 'avec gros blocs', 'con grossi blocchi', 10),
                ('lithology_uncon_secondary', 'bo', 'blocky / with blocks', 'blockig / mit Blöcken', 'bloqué / avec blocs', 'con blocchi', 20),
                ('lithology_uncon_secondary', 'co', 'stony / with stones', 'steinig / mit Steinen', 'pierreux / avec pierres', 'sassoso / con pietre', 30),
                ('lithology_uncon_secondary', 'gr', 'gravelly', 'kiesig', 'graveleux', 'ghiaioso', 35),
                ('lithology_uncon_secondary', 'fgr', 'fine gravelly', 'feinkiesig', 'graveleux fin', 'ghiaioso fine', 40),
                ('lithology_uncon_secondary', 'fmgr', 'fine to medium gravelly', 'fein- bis mittelkiesig', 'graveleux fin à moyen', 'ghiaioso fine-media', 50),
                ('lithology_uncon_secondary', 'mgr', 'medium gravelly', 'mittelkiesig', 'graveleux moyen', 'ghiaioso medio', 60),
                ('lithology_uncon_secondary', 'mcgr', 'medium to coarse gravelly', 'mittel- bis grobkiesig', 'graveleux moyen à grossier', 'ghiaioso medio-grosso', 70),
                ('lithology_uncon_secondary', 'cgr', 'coarse gravelly', 'grobkiesig', 'graveleux grossier', 'ghiaioso grosso', 80),
                ('lithology_uncon_secondary', 'sa', 'sandy', 'sandig', 'sableux', 'sabbioso', 85),
                ('lithology_uncon_secondary', 'fsa', 'fine sandy', 'feinsandig', 'sableux fin', 'sabbioso fine', 90),
                ('lithology_uncon_secondary', 'fmsa', 'fine to medium sandy', 'fein- bis mittelsandig', 'sableux fin à moyen', 'sabbioso fine-media', 100),
                ('lithology_uncon_secondary', 'msa', 'medium sandy', 'mittelsandig', 'sableux moyen', 'sabbioso medio', 110),
                ('lithology_uncon_secondary', 'mcsa', 'medium to coarse sandy', 'mittel- bis grobsandig', 'sableux moyen à grossier', 'sabbioso medio-grosso', 120),
                ('lithology_uncon_secondary', 'csa', 'coarse sandy', 'grobsandig', 'sableux grossier', 'sabbioso grosso', 130),
                ('lithology_uncon_secondary', 'si', 'silty', 'siltig', 'limoneux', 'limoso', 140),
                ('lithology_uncon_secondary', 'cl', 'clayey', 'tonig', 'argileux', 'argilloso', 150),
                ('lithology_uncon_secondary', 'or', 'with organic inclusion', 'organische Beimengung', 'avec inclusion organique', 'con inclusione organica', 160),
                ('lithology_uncon_secondary', 'oth', 'other', 'anderer', 'autre', 'altro', 170),
                ('lithology_uncon_secondary', 'ns', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 180);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('component_uncon_organic', '', 'earth', 'Erde', 'terre', 'terra', 10),
                ('component_uncon_organic', '', 'humus', 'Humus', 'humus', 'humus', 20),
                ('component_uncon_organic', '', 'undifferenciated organic material', 'Organische Beimegungen undifferiziert', 'matière organique indifférenciée', 'materia organica indifferenziata', 30),
                ('component_uncon_organic', '', 'roots', 'Wurzeln', 'racines', 'radici', 40),
                ('component_uncon_organic', '', 'remains of wood', 'Holzreste', 'morceaux de bois', 'resti di legno', 50),
                ('component_uncon_organic', '', 'remains of plants', 'Pflanzenreste', 'restes de plantes', 'resti vegetali', 60),
                ('component_uncon_organic', '', 'coal', 'Kohle', 'charbon', 'carbone', 70),
                ('component_uncon_organic', '', 'peat', 'Torf', 'tourbe', 'torba', 80),
                ('component_uncon_organic', '', 'varves', 'Varven', 'varves', 'varve', 90),
                ('component_uncon_organic', '', 'other', 'andere', 'autre', 'altro', 100),
                ('component_uncon_organic', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 110);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('component_uncon_debris', '', 'erratic block', 'Findling', 'bloc erratique', 'blocco erratico', 10),
                ('component_uncon_debris', '', 'rubble', 'Gerölle', 'gravats', 'detriti', 20),
                ('component_uncon_debris', '', 'bed load', 'Geschiebe', 'galets', 'materiale detritico non differenziato', 30),
                ('component_uncon_debris', '', 'fragments, splitters', 'Bruchstücke, Splitter', 'fragments, éclats', 'frammenti', 40),
                ('component_uncon_debris', '', 'tufa', 'Tuff', 'tuf', 'tufo', 50),
                ('component_uncon_debris', '', 'other', 'andere', 'autre', 'altro', 60),
                ('component_uncon_debris', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 70);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli,  text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('color', '', 'black', 'schwarz', 'noir', 'nero', 10),
                ('color', '', 'blackish grey', 'schwarzgrau', 'gris noirâtre', 'grigio nerastro', 20),
                ('color', '', 'dark grey', 'dunkelgrau', 'gris foncé', 'grigio scuro', 30),
                ('color', '', 'grey', 'grau', 'gris', 'grigio', 40),
                ('color', '', 'light grey', 'hellgrau', 'gris clair', 'grigio chiaro', 50),
                ('color', '', 'whitish grey', 'weissgrau', 'gris blanchâtre', 'grigio biancastro', 60),
                ('color', '', 'beige grey', 'beigegrau', 'gris-beige', 'grigio beige', 70),
                ('color', '', 'brownish grey', 'braungrau', 'gris brunâtre', 'grigio brunastro', 80),
                ('color', '', 'reddish grey', 'rotgrau', 'gris rougeâtre', 'grigio rossastro', 90),
                ('color', '', 'yellowish grey', 'gelbgrau', 'gris jaunâtre', 'grigio giallastro', 100),
                ('color', '', 'greenish grey', 'grüngrau', 'gris verdâtre', 'grigio verdastro', 110),
                ('color', '', 'bluish grey', 'blaugrau', 'gris bleuâtre', 'grigio bluastro', 120),
                ('color', '', 'pinkish grey', 'rosagrau', 'gris rosâtre', 'grigio rosastro', 130),
                ('color', '', 'white', 'weiss', 'blanc', 'bianco', 140),
                ('color', '', 'yellowish white', 'gelbweiss', 'blanc jaunâtre', 'bianco giallastro', 150),
                ('color', '', 'pinkish white', 'rosaweiss', 'blanc rosâtre', 'bianco rosastro', 160),
                ('color', '', 'dark beige', 'dunkelbeige', 'beige foncé', 'beige scuro', 170),
                ('color', '', 'beige', 'beige', 'beige', 'beige', 180),
                ('color', '', 'light beige', 'hellbeige', 'beige clair', 'beige chiaro', 190),
                ('color', '', 'greyish beige', 'graubeige', 'beige grisâtre', 'beige grigiastro', 200),
                ('color', '', 'ochre beige', 'ockerbeige', 'beige-ocre', 'beige ocra', 210),
                ('color', '', 'orange beige', 'orangebeige', 'beige orangé', 'beige aranciato', 220),
                ('color', '', 'yellowish beige', 'gelbbeige', 'beige jaunâtre', 'beige giallastro', 230),
                ('color', '', 'greenish beige', 'grünbeige', 'beige verdâtre', 'beige verdastro', 240),
                ('color', '', 'pinkish beige', 'rosabeige', 'beige rosâtre', 'beige rosastro', 250),
                ('color', '', 'dark ochre', 'dunkelocker', 'ocre foncé', 'ocra scuro', 260),
                ('color', '', 'ochre', 'ocker', 'ocre', 'ocra', 270),
                ('color', '', 'light ochre', 'hellocker', 'ocre clair', 'ocra chiaro', 280),
                ('color', '', 'reddish ochre', 'rotocker', 'ocre rougeâtre', 'ocra rossastro', 290),
                ('color', '', 'dark brown', 'dunkelbraun', 'brun foncé', 'marrone scuro', 300),
                ('color', '', 'brown', 'braun', 'brun', 'marrone', 310),
                ('color', '', 'light brown', 'hellbraun', 'brun clair', 'marrone chiaro', 320),
                ('color', '', 'blackish brown', 'schwarzbraun', 'brun noirâtre', 'marrone nerastro', 330),
                ('color', '', 'greyish brown', 'graubraun', 'brun grisâtre', 'marrone grigiastro', 340),
                ('color', '', 'ochre brown', 'ockerbraun', 'brun-ocre', 'marrone ocra', 350),
                ('color', '', 'reddish brown', 'rotbraun', 'brun rougeâtre', 'marrone rossiccio', 360),
                ('color', '', 'yellowish brown', 'gelbbraun', 'brun jaunâtre', 'marrone giallastro', 370),
                ('color', '', 'greenish brown', 'grünbraun', 'brun verdâtre', 'marrone verdastro', 380),
                ('color', '', 'olive brown', 'olivbraun', 'brun olivâtre', 'marrone olivastro', 390),
                ('color', '', 'dark red', 'dunkelrot', 'rouge foncé', 'rosso scuro', 400),
                ('color', '', 'red', 'rot', 'rouge', 'rosso', 410),
                ('color', '', 'light red', 'hellrot', 'rouge clair', 'rosso chiaro', 420),
                ('color', '', 'brownish red', 'braunrot', 'rouge brunâtre', 'rosso brunastro', 430),
                ('color', '', 'yellowish red', 'gelbrot', 'rouge jaunâtre', 'rosso giallastro', 440),
                ('color', '', 'bluish red', 'blaurot', 'rouge bleuâtre', 'rosso bluastro', 450),
                ('color', '', 'pinkish red', 'rosarot', 'rouge rosâtre', 'rosso rosastro', 460),
                ('color', '', 'dark orange', 'dunkelorange', 'orange foncé', 'arancio scuro', 470),
                ('color', '', 'orange', 'orange', 'orange', 'arancio', 480),
                ('color', '', 'light orange', 'hellorange', 'orange clair', 'arancio chiaro', 490),
                ('color', '', 'brownish orange', 'braunorange', 'orange brunâtre', 'arancio brunastro', 500),
                ('color', '', 'reddish orange', 'rotorange', 'orange rougeâtre', 'arancio rossastro', 510),
                ('color', '', 'yellowish orange', 'gelborange', 'orange jaunâtre', 'arancio giallastro', 520),
                ('color', '', 'pinkish orange', 'rosaorange', 'orange rosâtre', 'arancio rosastro', 530),
                ('color', '', 'dark yellow', 'dunkelgelb', 'jaune foncé', 'giallo scuro', 540),
                ('color', '', 'yellow', 'gelb', 'jaune', 'giallo', 550),
                ('color', '', 'light yellow', 'hellgelb', 'jaune clair', 'giallo chiaro', 560),
                ('color', '', 'greyish yellow', 'graugelb', 'jaune grisâtre', 'giallo grigiastro', 570),
                ('color', '', 'beige yellow', 'beigegelb', 'jaune-beige', 'giallo beige', 580),
                ('color', '', 'ochre yellow', 'ockergelb', 'jaune-ocre', 'giallo ocra', 590),
                ('color', '', 'brownish yellow', 'braungelb', 'jaune brunâtre', 'giallo brunastro', 600),
                ('color', '', 'reddish yellow', 'rotgelb', 'jaune rougeâtre', 'giallo rossastro', 610),
                ('color', '', 'olive yellow', 'olivgelb', 'jaune olivâtre', 'giallo olivastro', 620),
                ('color', '', 'dark green', 'dunkelgrün', 'vert foncé', 'verde scuro', 630),
                ('color', '', 'green', 'grün', 'vert', 'verde', 640),
                ('color', '', 'light green', 'hellgrün', 'vert clair', 'verde chiaro', 650),
                ('color', '', 'greyish green', 'graugrün', 'vert grisâtre', 'verde grigiastro', 660),
                ('color', '', 'yellowish green', 'gelbgrün', 'vert jaunâtre', 'verde giallastro', 670),
                ('color', '', 'olive green', 'olivgrün', 'vert olivâtre', 'verde olivastro', 680),
                ('color', '', 'bluish green', 'blaugrün', 'vert bleuâtre', 'verde bluastro', 690),
                ('color', '', 'dark olive', 'dunkeloliv', 'olive foncé', 'oliva scuro', 700),
                ('color', '', 'olive', 'oliv', 'olive', 'oliva', 710),
                ('color', '', 'light olive', 'helloliv', 'olive clair', 'oliva chiaro', 720),
                ('color', '', 'dark blue', 'dunkelblau', 'bleu foncé', 'blu scuro', 730),
                ('color', '', 'blue', 'blau', 'bleu', 'blu', 740),
                ('color', '', 'light blue', 'hellblau', 'bleu clair', 'blu chiaro', 750),
                ('color', '', 'greyish blue', 'graublau', 'bleu grisâtre', 'blu grigiastro', 760),
                ('color', '', 'greenish blue', 'grünblau', 'bleu verdâtre', 'blu verdastro', 770),
                ('color', '', 'dark violet', 'dunkelviolett', 'violet foncé', 'viola scuro', 780),
                ('color', '', 'violet', 'violett', 'violet', 'viola', 790),
                ('color', '', 'light violet', 'hellviolett', 'violet clair', 'viola chiaro', 800),
                ('color', '', 'greyish violet', 'grauviolett', 'violet grisâtre', 'viola grigiastro', 810),
                ('color', '', 'greenish violet', 'grünviolett', 'violet verdâtre', 'viola verdastro', 820),
                ('color', '', 'dark magenta', 'dunkelmagenta', 'magenta foncé', 'magenta scuro', 830),
                ('color', '', 'magenta', 'magenta', 'magenta', 'magenta', 840),
                ('color', '', 'light magenta', 'hellmagenta', 'magenta clair', 'magenta chiaro', 850),
                ('color', '', 'dark pink', 'dunkelrosa', 'rose foncé', 'rosa scuro', 860),
                ('color', '', 'pink', 'rosa', 'rose', 'rosa', 870),
                ('color', '', 'light pink', 'hellrosa', 'rose clair', 'rosa chiaro', 880),
                ('color', '', 'greyish pink', 'graurosa', 'rose grisâtre', 'rosa grigiastro', 890),
                ('color', '', 'other', 'andere', 'autre', 'altro', 900),
                ('color', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 910);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('rock_condition', '', 'disaggregated', 'zerfallen', 'desagrégé', 'disintegrato', 10),
                ('rock_condition', '', 'decomposed', 'zersetzt', 'décomposé', 'decomposto', 20),
                ('rock_condition', '', 'subsided', 'versackt', 'tassé', 'sprofondato', 30),
                ('rock_condition', '', 'displaced', 'verschleppt', 'déplacé', 'dislocato', 40),
                ('rock_condition', '', 'glided', 'gerutscht', 'glissé', 'scivolato', 50),
                ('rock_condition', '', 'other', 'anderer', 'autre', 'altro', 60),
                ('rock_condition', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 70);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('alteration_degree', '', 'fresh', 'frisch', 'sain', 'fresco', 10),
                ('alteration_degree', '', 'slightly weathered', 'schwach verwittert', 'peu altéré', 'poco alterato', 20),
                ('alteration_degree', '', 'moderately weathered', 'mässig verwittert', 'moyennement altéré', 'moderatamente alterato', 30),
                ('alteration_degree', '', 'highly weathered', 'stark verwittert', 'très altéré', 'molto alterato', 40),
                ('alteration_degree', '', 'completely weathered', 'vollständig verwittert', 'complètement altéré', 'completamente alterato', 50),
                ('alteration_degree', '', 'other', 'andere', 'autre', 'altro', 60),
                ('alteration_degree', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 70);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('component_con_particle', '', 'algae', 'Algen', 'algues', 'alghe', 10),
                ('component_con_particle', '', 'algal mats', 'Algenmatten', 'tapis algaires', 'strati algali', 20),
                ('component_con_particle', '', 'ammonites', 'Ammoniten', 'ammonites', 'ammoniti', 30),
                ('component_con_particle', '', 'aptychi', 'Aptychen', 'aptychi', 'aptychi', 40),
                ('component_con_particle', '', 'belemnites', 'Belemniten', 'belemnites', 'belemniti', 50),
                ('component_con_particle', '', 'bioclasts', 'Bioklasten', 'bioclastes', 'bioclasti', 60),
                ('component_con_particle', '', 'biodetritus', 'Biodetritus', 'biodétritus', 'biodetritus', 70),
                ('component_con_particle', '', 'bivalves', 'Muscheln', 'bivalves', 'bivalvi', 80),
                ('component_con_particle', '', 'brachiopods', 'Brachiopoden', 'brachiopodes', 'brachiopodi', 90),
                ('component_con_particle', '', 'bryozoans', 'Bryozoen', 'bryozoaires', 'briozoi', 100),
                ('component_con_particle', '', 'calpionellids', 'Calpionellen', 'calpionelles', 'calpionellidi', 110),
                ('component_con_particle', '', 'cephalopods', 'Kopffüsser', 'céphalopodes', 'cefalopodi', 120),
                ('component_con_particle', '', 'coccoliths', 'Coccolithen', 'coccolithes', 'coccoliti', 130),
                ('component_con_particle', '', 'corals', 'Korallen', 'coraux', 'coralli', 140),
                ('component_con_particle', '', 'crinoids', 'Crinoiden', 'crinoîdes', 'crinoidi', 150),
                ('component_con_particle', '', 'diatoms', 'Diatomeen', 'diatomées', 'diatomee', 160),
                ('component_con_particle', '', 'dinoflagellates', 'Dinoflagellaten', 'dinoflagellés', 'dinoflagellati', 170),
                ('component_con_particle', '', 'echinoderms', 'Echinodermen', 'échinodermes', 'echinodermi', 180),
                ('component_con_particle', '', 'echinoids', 'Seeigel', 'échinoïdes', 'echinoidi', 190),
                ('component_con_particle', '', 'fish remains', 'Fischreste', 'restes de poissons', 'resti di pesci', 200),
                ('component_con_particle', '', 'foraminifera', 'Foraminiferen', 'foraminifères', 'foraminiferi', 210),
                ('component_con_particle', '', 'fossils', 'Fossilien', 'fossiles', 'fossili', 220),
                ('component_con_particle', '', 'gastropods', 'Gastropoden', 'gastéropodes', 'gastropodi', 230),
                ('component_con_particle', '', 'gryphaea', 'Gryphaea', 'gryphaea', 'gryphaea', 240),
                ('component_con_particle', '', 'molluscs', 'Mollusken', 'mollusques', 'molluschi', 250),
                ('component_con_particle', '', 'nautilids', 'Nautiliden', 'nautilidés', 'nautilidi', 260),
                ('component_con_particle', '', 'nummulites', 'Nummuliten', 'nummulites', 'nummuliti', 270),
                ('component_con_particle', '', 'ostracods', 'Ostrakoden', 'ostracodes', 'ostracodi', 280),
                ('component_con_particle', '', 'oysters', 'Austern', 'huîtres', 'ostriche', 290),
                ('component_con_particle', '', 'radiolarians', 'Radiolarien', 'radiolaires', 'radiolari', 300),
                ('component_con_particle', '', 'rudists', 'Rudisten', 'rudistes', 'rudisti', 310),
                ('component_con_particle', '', 'Spicules', 'Spikulen', 'spicules', 'spicole', 320),
                ('component_con_particle', '', 'sponges', 'Schwämme', 'spongiaires', 'spugne', 330),
                ('component_con_particle', '', 'stromatolites', 'Stromatolithen', 'stromatolites', 'stromatoliti', 340),
                ('component_con_particle', '', 'tintinnids', 'Tintinniden', 'tintinnidés', 'tintinnidi', 350),
                ('component_con_particle', '', 'vertebrates', 'Wirbeltiere', 'vertébrés', 'vertebrati', 360),
                ('component_con_particle', '', 'ash', 'Asche', 'cendre', 'cenere', 370),
                ('component_con_particle', '', 'bitumen', 'Bitumen', 'bitume', 'bitume', 380),
                ('component_con_particle', '', 'calcareous concretion', 'Kalkkonkretion', 'concrétions calcaires', 'concrezioni calcaree', 390),
                ('component_con_particle', '', 'calcareous oncoids', 'Kalkonkoide', 'oncoïdes calcaires', 'oncoidi calcarei', 400),
                ('component_con_particle', '', 'calcareous ooids', 'Kalkooide', 'ooïdes calcaires', 'ooidi calcarei', 410),
                ('component_con_particle', '', 'calcareous pisoids', 'Kalkpisoide', 'pisoïdes calcaires', 'pisoidi calcarei', 420),
                ('component_con_particle', '', 'chert', 'Silexkonkretion', 'silex', 'selce', 430),
                ('component_con_particle', '', 'coal fragments', 'Kohlefragmente', 'fragments de charbon', 'frammenti di carbone', 440),
                ('component_con_particle', '', 'concretion', 'Konkretion', 'concrétion', 'concrezione', 450),
                ('component_con_particle', '', 'crystals', 'Kristalle', 'cristaux', 'cristalli', 460),
                ('component_con_particle', '', 'iron ooids', 'Eisenooide', 'ooïdes ferrugineux', 'ooidi ferruginosi', 470),
                ('component_con_particle', '', 'iron pisoids', 'Eisenpisoide', 'pisoïdes ferrugineux', 'pisoidi ferruginosi', 480),
                ('component_con_particle', '', 'lapilli', 'Lapilli', 'lapilli', 'lapilli', 490),
                ('component_con_particle', '', 'lithoclasts', 'Lithoklasten', 'lithoclastes', 'litoclasti', 500),
                ('component_con_particle', '', 'oncoids', 'Onkoide', 'oncoïdes', 'oncoidi', 510),
                ('component_con_particle', '', 'ooids', 'Ooide', 'ooïdes', 'ooidi', 520),
                ('component_con_particle', '', 'organic matter', 'Organische Substanz', 'matière organique', 'materia organica', 530),
                ('component_con_particle', '', 'pellets', 'Pellets', 'pellets', 'pellets', 540),
                ('component_con_particle', '', 'pisoids', 'Pisoide', 'pisoïdes', 'pisoidi', 550),
                ('component_con_particle', '', 'plant remains', 'Pflanzenreste', 'restes végétaux', 'resti vegetali', 560),
                ('component_con_particle', '', 'plant root tubes', 'Pflanzenwurzelröhren', 'tubes racinaires végétaux', 'tubi radicali vegetali', 570),
                ('component_con_particle', '', 'pollen', 'Pollen', 'pollen', 'polline', 580),
                ('component_con_particle', '', 'pyroclast', 'Pyroklast', 'pyroclaste', 'piroclasto', 590),
                ('component_con_particle', '', 'rootlets', 'Wurzelhaare', 'radicelles', 'radichette', 600),
                ('component_con_particle', '', 'sideritic concretion', 'Sideritkonkretion', 'concrétion de sidérite', 'concrezione di siderite', 610),
                ('component_con_particle', '', 'silicified wood', 'Versteinertes Holz', 'bois silicifié', 'legno silicizzato', 620),
                ('component_con_particle', '', 'spores', 'Sporen', 'spores', 'spore', 630),
                ('component_con_particle', '', 'wood fragments', 'Holzreste', 'fragments de bois', 'frammenti di legno', 640),
                ('component_con_particle', '', 'other', 'andere', 'autre', 'altro', 650),
                ('component_con_particle', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 660);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('component_con_mineral', '', 'actinolite', 'Aktinolith', 'actinote', 'actinolite', 10),
                ('component_con_mineral', '', 'adularia', 'Adular', 'adulaire', 'adularia', 20),
                ('component_con_mineral', '', 'albite', 'Albit', 'albite', 'albite', 30),
                ('component_con_mineral', '', 'almandine', 'Almandin', 'almandin', 'almandino', 40),
                ('component_con_mineral', '', 'amphibole', 'Amphibol', 'amphibole', 'anfibolo', 50),
                ('component_con_mineral', '', 'andalusite', 'Andalusit', 'andalousite', 'andalusite', 60),
                ('component_con_mineral', '', 'andesine', 'Andesin', 'andésine', 'andesina', 70),
                ('component_con_mineral', '', 'anhydrite', 'Anhydrit', 'anhydrite', 'anidrite', 80),
                ('component_con_mineral', '', 'ankerite', 'Ankerit', 'ankérite', 'ankerite', 90),
                ('component_con_mineral', '', 'anorthite', 'Anorthit', 'anorthite', 'anortite', 100),
                ('component_con_mineral', '', 'anorthoclase', 'Anorthoklas', 'anorthoclase', 'anortoclasio', 110),
                ('component_con_mineral', '', 'anthracite', 'Anthrazit', 'anthracite', 'antracite', 120),
                ('component_con_mineral', '', 'antigorite', 'Antigorit', 'antigorite', 'antigorite', 130),
                ('component_con_mineral', '', 'apatite', 'Apatit', 'apatite', 'apatite', 140),
                ('component_con_mineral', '', 'aragonite', 'Aragonit', 'aragonite', 'aragonite', 150),
                ('component_con_mineral', '', 'arsenopyrite', 'Arsenopyrit', 'arsénopyrite', 'arsenopirite', 160),
                ('component_con_mineral', '', 'asbestos', 'Asbest', 'amiante', 'amianto', 170),
                ('component_con_mineral', '', 'augite', 'Augit', 'augite', 'augite', 180),
                ('component_con_mineral', '', 'baryte', 'Baryt', 'barytine', 'barite', 190),
                ('component_con_mineral', '', 'bauxite', 'Bauxit', 'bauxite', 'bauxite', 200),
                ('component_con_mineral', '', 'biotite', 'Biotit', 'biotite', 'biotite', 210),
                ('component_con_mineral', '', 'calcite', 'Calcit', 'calcite', 'calcite', 220),
                ('component_con_mineral', '', 'cassiterite', 'Cassiterite', 'cassitérite', 'cassiterite', 230),
                ('component_con_mineral', '', 'celestine', 'Celestine', 'célestine', 'celestina', 240),
                ('component_con_mineral', '', 'chalcopyrite', 'Chalkopyrit', 'chalcopyrite', 'calcopirite', 250),
                ('component_con_mineral', '', 'chlorite', 'Chlorit', 'chlorite', 'clorite', 260),
                ('component_con_mineral', '', 'chloritoid', 'Chloritoid', 'chloritoïde', 'cloritoide', 270),
                ('component_con_mineral', '', 'chromite', 'Chromit', 'chromite', 'cromite', 280),
                ('component_con_mineral', '', 'chrysotile', 'Chrysotil', 'chrysotile', 'crisotilo', 290),
                ('component_con_mineral', '', 'coesite', 'Coesit', 'coésite', 'coesite', 300),
                ('component_con_mineral', '', 'copper', 'Kupfer', 'cuivre', 'rame', 310),
                ('component_con_mineral', '', 'cordierite', 'Cordierit', 'cordiérite', 'cordierite', 320),
                ('component_con_mineral', '', 'corundum', 'Korund', 'corindon', 'corindone', 330),
                ('component_con_mineral', '', 'diaspore', 'Diaspor', 'diaspore', 'diasporo', 340),
                ('component_con_mineral', '', 'diopside', 'Diopsid', 'diopside', 'diopside', 350),
                ('component_con_mineral', '', 'dolomite', 'Dolomit', 'dolomite', 'dolomite', 360),
                ('component_con_mineral', '', 'enstatite', 'Enstatit', 'enstatite', 'enstatite', 370),
                ('component_con_mineral', '', 'epidote', 'Epidot', 'épidote', 'epidoto', 380),
                ('component_con_mineral', '', 'feldspar', 'Feldspat', 'feldspath', 'feldspato', 390),
                ('component_con_mineral', '', 'fluorite', 'Fluorit', 'fluorine', 'fluorite', 400),
                ('component_con_mineral', '', 'forsterite', 'Forsterit', 'forstérite', 'forsterite', 410),
                ('component_con_mineral', '', 'fuchsite', 'Fuchsit', 'fuchsite', 'fuchsite', 420),
                ('component_con_mineral', '', 'galena', 'Galenit', 'galène', 'galena', 430),
                ('component_con_mineral', '', 'garnet', 'Granat', 'grenat', 'granato', 440),
                ('component_con_mineral', '', 'gibbsite', 'Gibbsit', 'gibbsite', 'gibbsite', 450),
                ('component_con_mineral', '', 'glauconite', 'Glaukonit', 'glauconite', 'glauconite', 460),
                ('component_con_mineral', '', 'glaucophane', 'Glaukophan', 'glaucophane', 'glaucofane', 470),
                ('component_con_mineral', '', 'goethite', 'Goethit', 'goethite', 'goethite', 480),
                ('component_con_mineral', '', 'gold', 'Gold', 'or', 'oro', 490),
                ('component_con_mineral', '', 'graphite', 'Graphit', 'graphite', 'grafite', 500),
                ('component_con_mineral', '', 'grossular', 'Grossular', 'grossulaire', 'grossularia', 510),
                ('component_con_mineral', '', 'gypsum', 'Gips', 'gypse', 'gesso', 520),
                ('component_con_mineral', '', 'halite', 'Halit', 'halite', 'halite', 530),
                ('component_con_mineral', '', 'hematite', 'Hämatit', 'hématite', 'ematite', 540),
                ('component_con_mineral', '', 'hornblende', 'Hornblende', 'hornblende', 'orneblenda', 550),
                ('component_con_mineral', '', 'illite', 'Illit', 'illite', 'illite', 560),
                ('component_con_mineral', '', 'ilmenite', 'Ilmenit', 'ilménite', 'ilmenite', 570),
                ('component_con_mineral', '', 'jadeite', 'Jadeit', 'jadéite', 'giadeite', 580),
                ('component_con_mineral', '', 'kaolinite', 'Kaolinit', 'kaolinite', 'caolinite', 590),
                ('component_con_mineral', '', 'K-feldspar', 'Kalifeldspat', 'feldspath potassique', 'feldspato potassico', 600),
                ('component_con_mineral', '', 'kyanite', 'Kyanit', 'kyanite', 'cianite', 610),
                ('component_con_mineral', '', 'leucite', 'Leucit', 'leucite', 'leucite', 620),
                ('component_con_mineral', '', 'lignite', 'Lignit', 'lignite', 'lignite', 630),
                ('component_con_mineral', '', 'limonite', 'Limonit', 'limonite', 'limonite', 640),
                ('component_con_mineral', '', 'magnesite', 'Magnesit', 'magnésite', 'magnesite', 650),
                ('component_con_mineral', '', 'magnetite', 'magnetit', 'magnétite', 'magnetite', 660),
                ('component_con_mineral', '', 'mica', 'Glimmer', 'mica', 'mica', 670),
                ('component_con_mineral', '', 'microcline', 'Mikroklin', 'microcline', 'microclino', 680),
                ('component_con_mineral', '', 'monazite', 'Monazit', 'monazite', 'monazite', 690),
                ('component_con_mineral', '', 'montmorillonite', 'Montmorillonit', 'montmorillonite', 'montmorillonite', 700),
                ('component_con_mineral', '', 'muscovite', 'Muskovit', 'muscovite', 'muscovite', 710),
                ('component_con_mineral', '', 'nepheline', 'Nephelin', 'néphéline', 'nefelina', 720),
                ('component_con_mineral', '', 'oligoclase', 'Oligoklas', 'oligoclase', 'oligoclasio', 730),
                ('component_con_mineral', '', 'olivine', 'Olivin', 'olivine', 'olivina', 740),
                ('component_con_mineral', '', 'omphacite', 'Omphazit', 'omphacite', 'omfacite', 750),
                ('component_con_mineral', '', 'orthoclase', 'Orthoklas', 'orthose', 'ortoclasio', 760),
                ('component_con_mineral', '', 'phengite', 'Phengit', 'phengite', 'fengite', 770),
                ('component_con_mineral', '', 'phlogopite', 'Phlogopit', 'phlogopite', 'flogopite', 780),
                ('component_con_mineral', '', 'plagioclase', 'Plagioklas', 'plagioclase', 'plagioclasio', 790),
                ('component_con_mineral', '', 'prehnite', 'Prehnit', 'prehnite', 'prehnite', 800),
                ('component_con_mineral', '', 'pyrite', 'Pyrit', 'pyrite', 'pirite', 810),
                ('component_con_mineral', '', 'pyrope', 'Pyrop', 'pyrope', 'piropo', 820),
                ('component_con_mineral', '', 'pyrophyllite', 'Pyrophyllit', 'pyrophyllite', 'pirofillite', 830),
                ('component_con_mineral', '', 'pyroxene', 'Pyroxen', 'pyroxène', 'pirosseno', 840),
                ('component_con_mineral', '', 'quartz', 'Quarz', 'quartz', 'quarzo', 850),
                ('component_con_mineral', '', 'rutile', 'Rutil', 'rutile', 'rutilo', 860),
                ('component_con_mineral', '', 'sapphirine', 'Sapphirin', 'sapphirine', 'saffirina', 870),
                ('component_con_mineral', '', 'scapolite', 'Skapolith', 'scapolite', 'scapolite', 880),
                ('component_con_mineral', '', 'sericite', 'Serizit', 'séricite', 'sericite', 890),
                ('component_con_mineral', '', 'serpentine', 'Serpentin', 'serpentine', 'serpentino', 900),
                ('component_con_mineral', '', 'siderite', 'Siderit', 'sidérite', 'siderite', 910),
                ('component_con_mineral', '', 'sillimanite', 'Sillimanit', 'sillimanite', 'sillimanite', 920),
                ('component_con_mineral', '', 'silver', 'Silber', 'argent', 'argento', 930),
                ('component_con_mineral', '', 'smectite', 'Smektit', 'smectite', 'smectite', 940),
                ('component_con_mineral', '', 'spessartite', 'Spessartin', 'spessartite', 'spessartina', 950),
                ('component_con_mineral', '', 'sphalerite', 'Sphalerit', 'sphalérite', 'sfalerite', 960),
                ('component_con_mineral', '', 'spinel', 'Spinell', 'spinelle', 'spinello', 970),
                ('component_con_mineral', '', 'staurolite', 'Staurolith', 'staurolite', 'staurolite', 980),
                ('component_con_mineral', '', 'stilpnomelane', 'Stilpnomelan', 'stilpnomélane', 'stilpnomelano', 990),
                ('component_con_mineral', '', 'sulfur', 'Sulfur', 'soufre', 'zolfo', 1000),
                ('component_con_mineral', '', 'talc', 'Talk', 'talc', 'talco', 1010),
                ('component_con_mineral', '', 'titanite', 'Titanit', 'titanite', 'titanite', 1020),
                ('component_con_mineral', '', 'tourmaline', 'Turmalin', 'tourmaline', 'tormalina', 1030),
                ('component_con_mineral', '', 'tremolite', 'Tremolit', 'trémolite', 'tremolite', 1040),
                ('component_con_mineral', '', 'vermiculite', 'Vermikulit', 'vermiculite', 'vermiculite', 1050),
                ('component_con_mineral', '', 'wollastonite', 'Wollastonit', 'wollastonite', 'wollastonite', 1060),
                ('component_con_mineral', '', 'zeolite', 'Zeolith', 'zéolite', 'zeolite', 1070),
                ('component_con_mineral', '', 'zircon', 'Zirkon', 'zircon', 'zircone', 1080),
                ('component_con_mineral', '', 'zoisite', 'Zoisit', 'zoïsite', 'zoisite', 1090),
                ('component_con_mineral', '', 'other', 'anderes', 'autre', 'altro', 1100),
                ('component_con_mineral', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 1110);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('cementation', '', 'uncemented', 'nicht zementiert', 'non cimenté', 'non cementato', 10),
                ('cementation', '', 'weakly cemented', 'schwach zementiert', 'faiblement cimenté', 'debolmente cementato', 20),
                ('cementation', '', 'moderately cemented', 'mässig zementiert', 'modérément cimenté', 'moderatamente cementato', 30),
                ('cementation', '', 'well cemented', 'gut zementiert', 'bien cimenté', 'ben cementato', 40),
                ('cementation', '', 'strongly cemented', 'stark zementiert', 'fortement cimenté', 'fortemente cementato', 50),
                ('cementation', '', 'other', 'andere', 'autre', 'altro', 60),
                ('cementation', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 70);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('structure_syn_gen', '', 'structureless', 'strukturlos', 'sans structure', 'senza struttura', 10),
                ('structure_syn_gen', '', 'nodular', 'knollig', 'nodulaire', 'nodulare', 20),
                ('structure_syn_gen', '', 'varves', 'Varven', 'varves', 'varve', 30),
                ('structure_syn_gen', '', 'bedded', 'geschichtet', 'stratifié', 'stratificato', 40),
                ('structure_syn_gen', '', 'slightly bedded', 'leicht geschichtet', 'légèrement stratifié', 'leggermente stratificato', 50),
                ('structure_syn_gen', '', 'moderatley bedded', 'mässig geschichtet', 'modérément stratifié', 'moderatamente stratificato', 60),
                ('structure_syn_gen', '', 'well bedded', 'gut geschichtet', 'bien stratifié', 'ben stratificato', 70),
                ('structure_syn_gen', '', 'very well bedded', 'sehr gut geschichtet', 'très bien stratifié', 'molto ben stratificato', 80),
                ('structure_syn_gen', '', 'laminated (< 1 cm)', 'laminiert (< 1 cm)', 'laminé (< 1 cm)', 'laminato (< 1 cm)', 90),
                ('structure_syn_gen', '', 'thin bedded (1 – 10 cm)', 'feinbankig (1 – 10 cm)', 'en couches minces (1 – 10 cm)', 'strato sottile (1 – 10 cm)', 100),
                ('structure_syn_gen', '', 'medium bedded (10 – 100 cm)', 'mittelbankig (10 – 100 cm)', 'en couches moyennes (10 – 100 cm)', 'strato medio (10 – 100 cm)', 110),
                ('structure_syn_gen', '', 'thick bedded (>100 cm)', 'dickbankig (>100 cm)', 'en couches épaisses (>100 cm)', 'strato spesso (>100 cm)', 120),
                ('structure_syn_gen', '', 'parallel bedding', 'parallele Schichtung', 'stratification parallèle', 'stratificazione parallela', 130),
                ('structure_syn_gen', '', 'non-parallel bedding', 'nicht parallele Schichtung', 'stratification non parallèle', 'stratificazione non parallela', 140),
                ('structure_syn_gen', '', 'wavy bedding (parallel)', 'wellige Schichtung (parallel)', 'stratification ondulée (parallèle)', 'stratificazione ondulata (parallela)', 150),
                ('structure_syn_gen', '', 'wavy bedding (irregular)', 'wellige Schichtung (unregelmässig)', 'stratification ondulée (irrégulière)', 'stratificazione ondulata (irregolare)', 160),
                ('structure_syn_gen', '', 'flaser bedding', 'Flaser-Schichtung', 'stratification flasée', 'stratificazione flaser', 170),
                ('structure_syn_gen', '', 'lenticular bedding', 'linsenförmige Schichtung', 'stratification lenticulaire', 'stratificazione lenticolare', 180),
                ('structure_syn_gen', '', 'pinch-and-swell bedding', 'pinch-and-swell Schichtung', 'stratification pinch-and-swell', 'stratificazione pinch-and-swell', 190),
                ('structure_syn_gen', '', 'crinkled', 'gekräuselt', 'froissée', 'increspata', 200),
                ('structure_syn_gen', '', 'graded bedding', 'gradierte Schichtung', 'granoclassement', 'stratificazione graduata', 210),
                ('structure_syn_gen', '', 'normal graded bedding', 'normal gradierte Schichtung', 'granoclassement normal', 'stratificazione graduata normale', 220),
                ('structure_syn_gen', '', 'inverse graded bedding', 'invers gradierte Schichtung', 'granoclassement inverse', 'stratificazione graduata inversa', 230),
                ('structure_syn_gen', '', 'cross-bedding', 'Kreuzschichtung', 'stratification entrecroisée', 'stratificazione incrociata', 240),
                ('structure_syn_gen', '', 'trough cross-bedding', 'Trogkreuzschichtung', 'stratification entrecroisée en auge', 'stratificazione incrociata a trogolo', 250),
                ('structure_syn_gen', '', 'festoon cross-bedding', 'Festoonkreuzschichtung', 'stratification entrecroisée en festons', 'stratificazione incrociata a festoni', 260),
                ('structure_syn_gen', '', 'tabular cross-bedding', 'tabulare Kreuzschichtung', 'stratification entrecroisée tabulaire', 'stratificazione incrociata tabulare', 270),
                ('structure_syn_gen', '', 'planar cross-bedding', 'planare Kreuzschichtung', 'stratification entrecroisée plane', 'stratificazione incrociata planare', 280),
                ('structure_syn_gen', '', 'ripples', 'Rippeln', 'ondulations', 'increspature', 290),
                ('structure_syn_gen', '', 'adhesion ripples', 'Adhäsionsrippeln', 'ondulations d''adhérence', 'increspature di adesione', 300),
                ('structure_syn_gen', '', 'asymmetrical ripples', 'asymmetrische Rippeln', 'ondulations asymétriques', 'increspature asimmetriche', 310),
                ('structure_syn_gen', '', 'planar/parallel ripples', 'planare/parallele Rippeln', 'ondulations planes/parallèles', 'increspature planari/parallele', 320),
                ('structure_syn_gen', '', 'symmetrical ripples', 'symmetrische Rippeln', 'ondulations symétriques', 'increspature simmetriche', 330),
                ('structure_syn_gen', '', 'ripple-drift, climbing ripples', 'Rippel-Drift,  Kletterrippeln', 'ondulations dérivantes,  ondulations ascendantes', 'increspature a deriva,  increspature rampanti', 340),
                ('structure_syn_gen', '', 'hummocky cross-stratification', 'hummockige Kreuzschichtung', 'stratification croisée bosselée', 'stratificazione incrociata a cumuli', 350),
                ('structure_syn_gen', '', 'flame structure', 'Flammenstruktur', 'structure en flammes', 'struttura a fiamma', 360),
                ('structure_syn_gen', '', 'dish structure', 'Dish-Struktur', 'structure en cuvette', 'struttura a piatto', 370),
                ('structure_syn_gen', '', 'load casts', 'Load casts', 'load casts', 'load casts', 380),
                ('structure_syn_gen', '', 'overturning bedding', 'überkippende Schichtung', 'stratification renversée', 'stratificazione sovrappendente', 390),
                ('structure_syn_gen', '', 'ptygmatic fold', 'ptygmatische Falte', 'pli ptygmatique', 'piega ptygmatica', 400),
                ('structure_syn_gen', '', 'convolute bedding', 'convolute Schichtung', 'stratification convolutée', 'stratificazione convoluta', 410),
                ('structure_syn_gen', '', 'slump/contorted bedding', 'Absackung/verdrehte Schichtung', 'affaissement/stratification contorsionnée', 'slump/stratificazione contorta', 420),
                ('structure_syn_gen', '', 'drag fold (sedimentary)', 'Schleppfalte (sedimentär)', 'pli de traînée (sédimentaire)', 'piegha di trascinamento (sedimentario)', 430),
                ('structure_syn_gen', '', 'dyke (sedimentary)', 'Dike (sedimentär)', 'dyke (sédimentaire)', 'dike (sedimentario)', 440),
                ('structure_syn_gen', '', 'clay drape', 'Lehmdrape', 'drapé argileux', 'drappeggio argilloso', 450),
                ('structure_syn_gen', '', 'flute casts', 'Flute casts', 'flute casts', 'flute casts', 460),
                ('structure_syn_gen', '', 'striation casts', 'Striation casts', 'striation casts', 'striation casts', 470),
                ('structure_syn_gen', '', 'groove casts', 'Groove casts', 'groove casts', 'groove casts', 480),
                ('structure_syn_gen', '', 'prod casts/bounce casts', 'Prod casts/bounce casts', 'prod casts/bounce casts', 'prod casts/bounce casts', 490),
                ('structure_syn_gen', '', 'mudcracks', 'Schlammrisse', 'craquelures de dessiccation', 'crepe fangose', 500),
                ('structure_syn_gen', '', 'syneresis cracks', 'Syneresisrisse', 'fissures de synérèse', 'crepe da sineresi', 510),
                ('structure_syn_gen', '', 'tepee structure', 'Tipi-Struktur', 'structure en tipi', 'struttura a tepee', 520),
                ('structure_syn_gen', '', 'pebble imbrication', 'Kieselimbrication', 'imbrication de galets', 'imbricazione di ciottoli', 530),
                ('structure_syn_gen', '', 'geopetal fabric', 'Geopetal', 'tissu géopétal', 'tessuto geopetalico', 540),
                ('structure_syn_gen', '', 'bioturbated', 'bioturbiert', 'bioturbé', 'bioturbato', 550),
                ('structure_syn_gen', '', 'burrows', 'biogene Wühlgänge', 'galeries biogènes', 'perforazione biogenica', 560),
                ('structure_syn_gen', '', 'boring', 'biogene Bohrung', 'percement biogène', 'gallerie biogeniche', 570),
                ('structure_syn_gen', '', 'bored surface', 'angebohrte Oberfläche', 'surface perforée', 'superficie perforata', 580),
                ('structure_syn_gen', '', 'other', 'andere', 'autre', 'altro', 590),
                ('structure_syn_gen', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 600);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('structure_post_gen', '', 'birdseye structure', 'Birdseye-Struktur', 'structure en œil d''oiseau', 'struttura birdseye', 10),
                ('structure_post_gen', '', 'fenestral structure', 'Fenestral-Struktur', 'structure en fenêtre', 'struttura fenestrata', 20),
                ('structure_post_gen', '', 'keystone vugs', 'Keystone-Hohlräume', 'cavités en clé de voûte', 'cavità keystone', 30),
                ('structure_post_gen', '', 'vugs', 'Hohlräume', 'cavités', 'cavità', 40),
                ('structure_post_gen', '', 'karst,  empty', 'Karst,  leer', 'karst,  vide', 'carsico, vuoto', 50),
                ('structure_post_gen', '', 'karst,  partially filled', 'Karst, teilweise gefüllt', 'karst, partiellement rempli', 'carsico, parzialmente riempito', 60),
                ('structure_post_gen', '', 'karst,  completely filled', 'Karst, vollständig gefüllt', 'karst, complètement rempli', 'carsico, completamente riempito', 70),
                ('structure_post_gen', '', 'caliche', 'Caliche', 'caliche', 'caliche', 80),
                ('structure_post_gen', '', 'hardground', 'Hartgrund', 'surface durcie', 'superficie indurita', 90),
                ('structure_post_gen', '', 'pseudomorphosis', 'Pseudomorphose', 'pseudomorphose', 'pseudomorfosi', 100),
                ('structure_post_gen', '', 'neomorphism', 'Neomorphose', 'néomorphisme', 'neomorfismo', 110),
                ('structure_post_gen', '', 'crystal ghosts', 'Phantomkristalle', 'fantômes cristallins', 'fantasmi di cristallini', 120),
                ('structure_post_gen', '', 'fossil ghosts', 'Phantomfossilien', 'fantômes fossiles', 'fantasmi di fossili', 130),
                ('structure_post_gen', '', 'ooid ghosts', 'Phantomooide', 'fantômes d’ooïdes', 'fantasmi di ooidi', 140),
                ('structure_post_gen', '', 'pressure solution seams', 'Drucklösungsnähte', 'joints de dissolution sous pression', 'suture di dissoluzione', 150),
                ('structure_post_gen', '', 'stylolites', 'Styrolithe', 'stylolites', 'stiloliti', 160),
                ('structure_post_gen', '', 'jointed', 'geklüftet', 'fissuré', 'fessurato', 170),
                ('structure_post_gen', '', 'faulted', 'gestört', 'faillé', 'fagliato', 180),
                ('structure_post_gen', '', 'fractured', 'frakturiert', 'fracturé', 'fratturato', 190),
                ('structure_post_gen', '', 'slickensides', 'Spiegelflächen (Slickensides)', 'surfaces lustrées (slickensides)', 'superfici levigate (slickensides)', 200),
                ('structure_post_gen', '', 'pull-apart structure', 'Pull-Apart-Struktur', 'structure en pull-apart', 'struttura a pull-apart', 210),
                ('structure_post_gen', '', 'glided', 'gerutscht', 'glissé', 'scivolato', 220),
                ('structure_post_gen', '', 'displaced', 'verschleppt', 'déplacé', 'dislocato', 230),
                ('structure_post_gen', '', 'subsided', 'versackt', 'tassé', 'sprofondato', 240),
                ('structure_post_gen', '', 'cataclastic', 'kataklastisch', 'cataclastique', 'cataclastico', 250),
                ('structure_post_gen', '', 'sheared', 'geschert', 'cisaillé', 'tagliato', 260),
                ('structure_post_gen', '', 'boudinage', 'Boudinage', 'boudinage', 'boudinage', 270),
                ('structure_post_gen', '', 'folded', 'gefaltet', 'plié', 'piegato', 280),
                ('structure_post_gen', '', 'mylonitic', 'mylonitisch', 'mylonitique', 'mylonitico', 290),
                ('structure_post_gen', '', 'blastomylonitic', 'blastomylonitisch', 'blastomylonitique', 'blastomylonitico', 300),
                ('structure_post_gen', '', 'vein', 'Ader', 'veine', 'vena', 310),
                ('structure_post_gen', '', 'gypsum vein', 'Gipsader', 'veine de gypse', 'vena di gesso', 320),
                ('structure_post_gen', '', 'anhydrite vein', 'Anhydritader', 'veine d''anhydrite', 'vena di anidrite', 330),
                ('structure_post_gen', '', 'fibrous gypsum', 'Flasergips', 'gypse fibreux', 'gesso fibroso', 340),
                ('structure_post_gen', '', 'anhydrite nodule layers (chicken-wire)', 'Netzanhydrit (Chicken‑Wire‑Anhydrit)', 'couches de nodules d''anhydrite (chicken-wire)', 'strati di noduli di anidrite (chicken-wire)', 350),
                ('structure_post_gen', '', 'collapse breccia', 'Einsturzbrekzie', 'brèche d’effondrement', 'breccia da crollo', 360),
                ('structure_post_gen', '', 'solution breccia', 'Lösungsbrekzie', 'brèche de dissolution', 'breccia da soluzione', 370),
                ('structure_post_gen', '', 'brecciated', 'brekziös', 'bréchique', 'brecciato', 380),
                ('structure_post_gen', '', 'rauhwacke', 'Rauhwacke', 'rauhwacke', 'rauhwacke', 390),
                ('structure_post_gen', '', 'cone-in-cone', 'Cone-in-Cone', 'cone-in-cone', 'cone-in-cone', 400),
                ('structure_post_gen', '', 'horse-tailing', 'Horse-Tailing', 'horse-tailing', 'horse-tailing', 410),
                ('structure_post_gen', '', 'other', 'andere', 'autre', 'altro', 420),
                ('structure_post_gen', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 430);

            INSERT INTO bdms.codelist(
                schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli
            ) VALUES
                ('texture_mata', '', 'massive', 'massig', 'massif', 'massiccio', 10),
                ('texture_mata', '', 'layered', 'laminiert', 'stratifié', 'stratificato', 20),
                ('texture_mata', '', 'foliated', 'foliiert', 'folié', 'foliata', 30),
                ('texture_mata', '', 'phyllitic', 'phyllitisch', 'phyllitique', 'fillitico', 40),
                ('texture_mata', '', 'schistose', 'schiefrig', 'schisteux', 'scistoso', 50),
                ('texture_mata', '', 'banded', 'gebändert', 'rubané', 'a bande', 60),
                ('texture_mata', '', 'platy', 'plattig', 'en plaquettes', 'a placche', 70),
                ('texture_mata', '', 'augen-textured', 'augig', 'à texture œillée', 'tessitura a forma di occhio', 80),
                ('texture_mata', '', 'lenticular', 'linsig', 'lenticulaire', 'lenticolare', 90),
                ('texture_mata', '', 'flaser-textured', 'flaserig', 'à texture flaser', 'tessitura flaser', 100),
                ('texture_mata', '', 'streaky', 'schlierig', 'strié', 'striato', 110),
                ('texture_mata', '', 'migmatitic', 'migmatitisch', 'migmatitique', 'migmatitico', 120),
                ('texture_mata', '', 'granoblastic', 'granoblastisch', 'granoblastique', 'granoblastico', 130),
                ('texture_mata', '', 'lepidoblastic', 'lepidoblastisch', 'lépidoblastique', 'lepidoblastico', 140),
                ('texture_mata', '', 'nematoblastic', 'nematoblastisch', 'nématoblastique', 'nematoblastico', 150),
                ('texture_mata', '', 'porphyroblastic', 'porphyroblastisch', 'porphyroblastique', 'porfiroblastico', 160),
                ('texture_mata', '', 'xenoblastic', 'xenoblastisch', 'xénoblastique', 'xenoblastico', 170),
                ('texture_mata', '', 'idioblastic', 'idioblastisch', 'idioblastique', 'idioblastico', 180),
                ('texture_mata', '', 'other', 'andere', 'autre', 'altro', 190),
                ('texture_mata', '', 'not specified', 'keine Angabe', 'sans indication', 'senza indicazioni', 200);
        ");
    }
}
#pragma warning restore CA1505
