using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BDMS.Migrations;

/// <inheritdoc />
public partial class MergeFilesAndBoreholeFilesIntoProfile : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // 1. Visibility - log counts of orphan rows being dropped.
        migrationBuilder.Sql(@"
DO $$
DECLARE
    orphan_count int;
    incomplete_count int;
BEGIN
    SELECT COUNT(*) INTO orphan_count
    FROM bdms.files f
    LEFT JOIN bdms.borehole_files bf ON bf.id_fil_fk = f.id_fil
    WHERE bf.id_fil_fk IS NULL;

    SELECT COUNT(*) INTO incomplete_count
    FROM bdms.borehole_files bf
    LEFT JOIN bdms.files f ON f.id_fil = bf.id_fil_fk
    WHERE f.id_fil IS NULL;

    RAISE NOTICE 'profile migration: dropping % orphan files row(s)', orphan_count;
    RAISE NOTICE 'profile migration: dropping % incomplete borehole_files row(s)', incomplete_count;
END $$;
");

        // 2. Create the new profile table (auto-generated by EF from the model).
        migrationBuilder.CreateTable(
            name: "profile",
            schema: "bdms",
            columns: table => new
            {
                id = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                borehole_id = table.Column<int>(type: "integer", nullable: false),
                name = table.Column<string>(type: "text", nullable: false),
                name_uuid = table.Column<string>(type: "text", nullable: false),
                type = table.Column<string>(type: "text", nullable: false),
                description = table.Column<string>(type: "text", nullable: true),
                @public = table.Column<bool>(name: "public", type: "boolean", nullable: true),
                creator = table.Column<int>(type: "integer", nullable: true),
                creation = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                updater = table.Column<int>(type: "integer", nullable: true),
                update = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_profile", x => x.id);
                table.ForeignKey(
                    name: "FK_profile_borehole_borehole_id",
                    column: x => x.borehole_id,
                    principalSchema: "bdms",
                    principalTable: "borehole",
                    principalColumn: "id_bho",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "FK_profile_users_creator",
                    column: x => x.creator,
                    principalSchema: "bdms",
                    principalTable: "users",
                    principalColumn: "id_usr");
                table.ForeignKey(
                    name: "FK_profile_users_updater",
                    column: x => x.updater,
                    principalSchema: "bdms",
                    principalTable: "users",
                    principalColumn: "id_usr");
            });

        // 3. Copy clean joins into profile, COALESCEing audit columns from whichever side held the value.
        migrationBuilder.Sql(@"
INSERT INTO bdms.profile (
    borehole_id, name, name_uuid, type,
    description, public,
    creator, creation, updater, ""update""
)
SELECT
    bf.id_bho_fk,
    f.name_fil,
    f.name_uuid_fil,
    f.type_fil,
    bf.description_bfi,
    bf.public_bfi,
    COALESCE(bf.id_usr_fk, f.id_usr_fk),
    COALESCE(bf.attached_bfi, f.uploaded_fil),
    COALESCE(bf.updater_bfi, f.updated_by_fil),
    COALESCE(bf.update_bfi, f.updated_fil)
FROM bdms.borehole_files bf
INNER JOIN bdms.files f ON f.id_fil = bf.id_fil_fk;
");

        // 4. Create indexes (auto-generated by EF for FK columns + manually-added UNIQUE on name_uuid).
        migrationBuilder.CreateIndex(
            name: "IX_profile_borehole_id",
            schema: "bdms",
            table: "profile",
            column: "borehole_id");

        migrationBuilder.CreateIndex(
            name: "IX_profile_creator",
            schema: "bdms",
            table: "profile",
            column: "creator");

        migrationBuilder.CreateIndex(
            name: "IX_profile_updater",
            schema: "bdms",
            table: "profile",
            column: "updater");

        migrationBuilder.CreateIndex(
            name: "IX_profile_name_uuid",
            schema: "bdms",
            table: "profile",
            column: "name_uuid",
            unique: true);

        // 5. Drop the join table first (it FKs into files).
        migrationBuilder.DropTable(
            name: "borehole_files",
            schema: "bdms");

        // 6. Drop the legacy files table.
        migrationBuilder.DropTable(
            name: "files",
            schema: "bdms");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Recreate files table.
        migrationBuilder.CreateTable(
            name: "files",
            schema: "bdms",
            columns: table => new
            {
                id_fil = table.Column<int>(type: "integer", nullable: false)
                    .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                id_usr_fk = table.Column<int>(type: "integer", nullable: true),
                updated_by_fil = table.Column<int>(type: "integer", nullable: true),
                updated_fil = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                name_fil = table.Column<string>(type: "text", nullable: false),
                name_uuid_fil = table.Column<string>(type: "text", nullable: true),
                type_fil = table.Column<string>(type: "text", nullable: false),
                uploaded_fil = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_files", x => x.id_fil);
                table.ForeignKey(
                    name: "FK_files_users_id_usr_fk",
                    column: x => x.id_usr_fk,
                    principalSchema: "bdms",
                    principalTable: "users",
                    principalColumn: "id_usr");
                table.ForeignKey(
                    name: "FK_files_users_updated_by_fil",
                    column: x => x.updated_by_fil,
                    principalSchema: "bdms",
                    principalTable: "users",
                    principalColumn: "id_usr");
            });

        // Recreate borehole_files join table.
        migrationBuilder.CreateTable(
            name: "borehole_files",
            schema: "bdms",
            columns: table => new
            {
                id_bho_fk = table.Column<int>(type: "integer", nullable: false),
                id_fil_fk = table.Column<int>(type: "integer", nullable: false),
                id_usr_fk = table.Column<int>(type: "integer", nullable: true),
                attached_bfi = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                created_bfi = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                created_by_bfi = table.Column<int>(type: "integer", nullable: true),
                update_bfi = table.Column<DateTime>(type: "timestamp without time zone", nullable: true),
                updater_bfi = table.Column<int>(type: "integer", nullable: true),
                description_bfi = table.Column<string>(type: "text", nullable: true),
                public_bfi = table.Column<bool>(type: "boolean", nullable: true),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_borehole_files", x => new { x.id_bho_fk, x.id_fil_fk });
                table.ForeignKey(
                    name: "borehole_files_id_bho_fk_fkey",
                    column: x => x.id_bho_fk,
                    principalSchema: "bdms",
                    principalTable: "borehole",
                    principalColumn: "id_bho",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "borehole_files_id_fil_fk_fkey",
                    column: x => x.id_fil_fk,
                    principalSchema: "bdms",
                    principalTable: "files",
                    principalColumn: "id_fil",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "FK_borehole_files_users_created_by_bfi",
                    column: x => x.created_by_bfi,
                    principalSchema: "bdms",
                    principalTable: "users",
                    principalColumn: "id_usr");
                table.ForeignKey(
                    name: "FK_borehole_files_users_id_usr_fk",
                    column: x => x.id_usr_fk,
                    principalSchema: "bdms",
                    principalTable: "users",
                    principalColumn: "id_usr");
                table.ForeignKey(
                    name: "FK_borehole_files_users_updater_bfi",
                    column: x => x.updater_bfi,
                    principalSchema: "bdms",
                    principalTable: "users",
                    principalColumn: "id_usr");
            });

        migrationBuilder.CreateIndex(
            name: "IX_borehole_files_id_bho_fk",
            schema: "bdms",
            table: "borehole_files",
            column: "id_bho_fk");

        migrationBuilder.CreateIndex(
            name: "IX_borehole_files_id_fil_fk",
            schema: "bdms",
            table: "borehole_files",
            column: "id_fil_fk");

        // Reconstitute file rows from profiles.
        migrationBuilder.Sql(@"
INSERT INTO bdms.files (id_fil, id_usr_fk, updated_by_fil, updated_fil, name_fil, name_uuid_fil, type_fil, uploaded_fil)
SELECT id, creator, updater, ""update"", name, name_uuid, type, creation
FROM bdms.profile;
");

        // Reconstitute borehole_files rows.
        migrationBuilder.Sql(@"
INSERT INTO bdms.borehole_files (id_bho_fk, id_fil_fk, id_usr_fk, attached_bfi, description_bfi, public_bfi, created_bfi, created_by_bfi, update_bfi, updater_bfi)
SELECT borehole_id, id, creator, creation, description, public, creation, creator, ""update"", updater
FROM bdms.profile;
");

        // Drop the profile table.
        migrationBuilder.DropTable(
            name: "profile",
            schema: "bdms");
    }
}
