// <auto-generated />
using System;
using BDMS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BDMS.Migrations
{
    [DbContext(typeof(BdmsContext))]
    partial class BdmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bdms")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BDMS.Models.Codelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cli");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_cli");

                    b.Property<string>("Conf")
                        .HasColumnType("text")
                        .HasColumnName("conf_cli");

                    b.Property<bool?>("Default")
                        .HasColumnType("boolean")
                        .HasColumnName("default_cli");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("text")
                        .HasColumnName("description_cli_de");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_cli_en");

                    b.Property<string>("DescriptionFr")
                        .HasColumnType("text")
                        .HasColumnName("description_cli_fr");

                    b.Property<string>("DescriptionIt")
                        .HasColumnType("text")
                        .HasColumnName("description_cli_it");

                    b.Property<string>("DescriptionRo")
                        .HasColumnType("text")
                        .HasColumnName("description_cli_ro");

                    b.Property<int?>("Geolcode")
                        .HasColumnType("integer")
                        .HasColumnName("geolcode");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order_cli");

                    b.Property<string>("Schema")
                        .HasColumnType("text")
                        .HasColumnName("schema_cli");

                    b.Property<string>("TextDe")
                        .HasColumnType("text")
                        .HasColumnName("text_cli_de");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_cli_en");

                    b.Property<string>("TextFr")
                        .HasColumnType("text")
                        .HasColumnName("text_cli_fr");

                    b.Property<string>("TextIt")
                        .HasColumnType("text")
                        .HasColumnName("text_cli_it");

                    b.Property<string>("TextRo")
                        .HasColumnType("text")
                        .HasColumnName("text_cli_ro");

                    b.HasKey("Id");

                    b.ToTable("codelist", "bdms");
                });
#pragma warning restore 612, 618
        }
    }
}
