name: Chart Lint

on:
  pull_request:
    paths:
      - "charts/**"
      - "environments/**"
      - "ct.yaml"
      - ".github/workflows/chart-lint.yml"
  push:
    branches:
      - main
    paths:
      - "charts/**"
      - "environments/**"
      - "ct.yaml"
      - ".github/workflows/chart-lint.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Lint main chart
        run: ct lint --config ct.yaml --charts charts/swissgeol-boreholes

      - name: Lint sync charts
        run: ct lint --config ct.yaml --charts charts/swissgeol-boreholes-extern-sync,charts/swissgeol-boreholes-view-sync

      - name: Validate int environment values
        run: |
          helm lint charts/swissgeol-boreholes -f environments/int/boreholes.values.yaml
          helm lint charts/swissgeol-boreholes -f environments/int/boreholes.values.yaml -f environments/int/boreholes-ext.values.yaml
          helm lint charts/swissgeol-boreholes -f environments/int/boreholes.values.yaml -f environments/int/boreholes-view.values.yaml
          helm lint charts/swissgeol-boreholes-extern-sync -f environments/int/extern-sync.values.yaml
          helm lint charts/swissgeol-boreholes-view-sync -f environments/int/view-sync.values.yaml

      - name: Validate prod environment values
        run: |
          helm lint charts/swissgeol-boreholes -f environments/prod/boreholes.values.yaml
          helm lint charts/swissgeol-boreholes -f environments/prod/boreholes.values.yaml -f environments/prod/boreholes-ext.values.yaml
          helm lint charts/swissgeol-boreholes -f environments/prod/boreholes.values.yaml -f environments/prod/boreholes-view.values.yaml
          helm lint charts/swissgeol-boreholes-extern-sync -f environments/prod/extern-sync.values.yaml
          helm lint charts/swissgeol-boreholes-view-sync -f environments/prod/view-sync.values.yaml
