name: Deploy Dev

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to dev cluster
    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ vars.DEV_AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.DEV_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Deploy to dev
        env:
          VERSION: ${{ inputs.version }}
        run: |
          helm upgrade swissgeol-boreholes ./charts/swissgeol-boreholes \
            --set app.version="$VERSION" \
            -n swissgeol-boreholes \
            --install --wait --timeout 5m
