name: Deploy Prod

on:
  workflow_dispatch:
    inputs:
      chart-version:
        description: "Chart version to deploy (leave empty for latest)"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to prod cluster (${{ matrix.release }})
    environment: prod

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        include:
          - release: swissgeol-boreholes
            chart: swissgeol-boreholes
            namespace: swissgeol-boreholes
            values: -f environments/prod/boreholes.values.yaml
          - release: swissgeol-boreholes-ext
            chart: swissgeol-boreholes
            namespace: swissgeol-boreholes-ext
            values: -f environments/prod/boreholes.values.yaml -f environments/prod/boreholes-ext.values.yaml
          - release: swissgeol-boreholes-view
            chart: swissgeol-boreholes
            namespace: swissgeol-boreholes-view
            values: -f environments/prod/boreholes.values.yaml -f environments/prod/boreholes-view.values.yaml
          - release: swissgeol-boreholes-extern-sync
            chart: swissgeol-boreholes-extern-sync
            namespace: swissgeol-boreholes-extern-sync
            values: -f environments/prod/extern-sync.values.yaml
          - release: swissgeol-boreholes-view-sync
            chart: swissgeol-boreholes-view-sync
            namespace: swissgeol-boreholes-view-sync

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ vars.PROD_AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.PROD_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Deploy
        env:
          CHART_VERSION: ${{ inputs.chart-version }}
        run: |
          helm repo add swissgeol https://swisstopo.github.io/swissgeol-boreholes-suite/
          helm repo update
          helm upgrade ${{ matrix.release }} swissgeol/${{ matrix.chart }} \
            ${CHART_VERSION:+--version "$CHART_VERSION"} \
            ${{ matrix.values }} \
            -n ${{ matrix.namespace }} \
            --install --wait --timeout 5m
