name: Deploy Dev

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      AWS_ROLE_DEV:
        required: true
      AWS_REGION:
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to dev cluster
    environment: dev

    env:
      KUBECONFIG: ${{ github.workspace }}/.kube/config

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws eks update-kubeconfig --name dev --region "$AWS_REGION"

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Deploy to dev
        env:
          VERSION: ${{ inputs.version }}
        run: |
          helm upgrade swissgeol-boreholes ./charts/swissgeol-boreholes \
            -f environments/dev/boreholes.values.yaml \
            --set app.version="$VERSION" \
            -n swissgeol-boreholes \
            --kubeconfig "$KUBECONFIG" \
            --install --wait --timeout 5m
